### ISSUE TITLE
State of nng and this wrapper?

### ISSUE THREAD

**Issue by Notmeor** [neachdainn/nng-rs#2]
Haven't seen active work recently both on nng and this wrapper, is it because they have already reached a stable state, or some other reason?
Is this wrapper( and nng) production-ready, how would you suggest?

**Comment by neachdainn** [comment]
[Tracking issue: Gitlab 40][3]

NNG is definitely both production ready and stable. It is at v1.1.1 and Garret is adamant that it follows SemVer.

This wrapper is in a state of "[it does everything I need it to, just giving it time for feedback to happen][1]." My plan was to bump the version to v1.0 with the release of NNG v1.2 as there is a [bug][2] in NNG v1.1.1 that completely breaks my (unusual) usage of REQREP sockets.

[1]: https://gitlab.com/neachdainn/nng-rs/issues/36
[2]: https://github.com/nanomsg/nng/issues/931
[3]: https://gitlab.com/neachdainn/nng-rs/issues/40

**Comment by Notmeor** [comment]
Nice to hear that. Would definitely appreciate the v1.0 release!
