### ISSUE TITLE
Muti-part message?

### ISSUE THREAD

**Issue by Notmeor** [neachdainn/nng-rs#3]
When using pub/sub, [the topics that subscribers subscribe to is just the first part of the message body. Applications should construct their messages accordingly.](https://nanomsg.github.io/nng/man/v1.1.0/nng_sub.7).

But how to send multi-part messages with nng-rs?

**Comment by neachdainn** [comment]
Nanomsg/NNG does not have multi-part messages. What that section of the manual is saying is that the beginning of the message will be compared against the subscribed topics and that you, as the user of NNG, need to decide how the topics will be accounted for.

When I'm using PUBSUB, I almost always know the number of topics that will exist through the life of the socket and I encode it as the first `u32` of the message. E.g.,

```rust
enum Topic {
    Camera = 1,
    Torque = 2,
}

// Publisher
let topic = (Topic::Camera as u32).to_le_bytes();
let content = Camera::get_image();

let mut msg = Message::new();
msg.push_back(&topic);
msg.push_back(content);

publisher.send(msg);

// Subscriber
subscriber.set_opt::<Subscribe>((Topic::Camera as u32).to_le_bytes());
let msg = subscriber.recv();

let (topic, content) = (msg[..4], msg[4..]);
```

The above probably won't compile but should give you the right idea.

**Comment by Notmeor** [comment]
I see. Users just prepend topics to messages.
